version: "3.8"

services:
  strapi:
    image: ${DOCKERHUB_USERNAME}/portfolio-backend:latest
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=data/sqlite.db
      # Variables de entorno requeridas para producción
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      # Volumen persistente para datos
      - strapi_data:/app/data
      # Opcional: volumen para uploads
      - strapi_uploads:/app/public/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/admin"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  strapi_data:
    driver: local
  strapi_uploads:
    driver: local
